/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue API token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke current token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserMeEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List departments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepartmentListEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Create department (settings)
         * @description Requires settings.departments.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DepartmentWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepartmentEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete department (settings)
         * @description Requires settings.departments. Fails with 422 if employees or users are linked.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Department has linked employees or users */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update department (settings)
         * @description Requires settings.departments.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DepartmentWrite"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepartmentEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated users (settings)
         * @description Requires settings.users.
         */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    per_page?: components["parameters"]["perPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserAdminPaginatedEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Create user (settings)
         * @description Requires settings.users.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserAdminCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserAdminEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update user (settings)
         * @description Requires settings.users.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserAdminUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserAdminEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/users/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set user active flag (settings)
         * @description Requires settings.users. Revokes tokens when deactivating.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserAdminActiveBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserAdminEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/legal-parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List legal parameters effective at reference date
         * @description Requires settings.params. Query `at` defaults to today (YYYY-MM-DD).
         */
        get: {
            parameters: {
                query?: {
                    at?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LegalParametersListEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal-parameters/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update legal parameter value / vigencia
         * @description Requires settings.params.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LegalParameterUpdateBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LegalParameterEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles with permissions
         * @description Requires settings.users. Each role includes permission rows from RBAC.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoleListEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated employees */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    per_page?: components["parameters"]["perPage"];
                    search?: string;
                    status?: components["schemas"]["EmployeeStatus"];
                    department_id?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeePaginatedEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create employee */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        /** Get employee */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete employee */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update employee */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeWritePartial"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/employees/{id}/termination": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        /**
         * Get employee termination record if any
         * @description Requires employees.view and department access.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeTerminationEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * Create termination (draft or confirm)
         * @description Requires employees.offboard and department access. When confirm is true (default), sets employee to cesado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeTerminationWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeTerminationEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Confirm draft termination
         * @description Requires employees.offboard and department access.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeTerminationEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/employees/{id}/termination/liquidation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        /**
         * Get liquidation snapshot for termination case
         * @description Requires employees.view and department access. Returns data null if no snapshot saved yet.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeTerminationLiquidationEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Create or replace liquidation snapshot
         * @description Requires employees.offboard and department access. Manual amounts only; no legal engine. Server sets recorded_at.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeTerminationLiquidationWrite"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeTerminationLiquidationSavedEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/termination/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate termination certificate PDF
         * @description Requires employees.offboard and department access. Confirmed termination only. Stores PDF as employee document type termination_certificate; download via existing document file endpoint.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeDocumentEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/termination/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        /**
         * List offboarding checklist tasks for termination case
         * @description Requires employees.view and department access. Creates tasks from catalog if missing. Includes assigned_assets (rows with employee_id = this employee) for operational return tracking.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeTerminationChecklistListEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/termination/checklist/tasks/{task}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
                task: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update checklist task (complete/pending and optional note)
         * @description Requires employees.offboard and department access.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                    task: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeTerminationChecklistTaskWrite"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeTerminationChecklistTaskEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/employees/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        /** List documents */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeDocumentListEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Upload document */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        type: components["schemas"]["EmployeeDocumentType"];
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeDocumentEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete document */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    documentId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List attendance records */
        get: {
            parameters: {
                query?: {
                    employee_id?: number;
                    from?: string;
                    to?: string;
                    page?: components["parameters"]["page"];
                    per_page?: components["parameters"]["perPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttendancePaginatedEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create attendance record */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AttendanceWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttendanceEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update attendance record */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AttendancePatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttendanceEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/vacation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vacation requests */
        get: {
            parameters: {
                query?: {
                    employee_id?: number;
                    status?: components["schemas"]["VacationStatus"];
                    page?: components["parameters"]["page"];
                    per_page?: components["parameters"]["perPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VacationPaginatedEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create vacation request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VacationWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VacationEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacation-requests/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update request status */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VacationStatusPatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VacationEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/payroll-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payroll periods */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PayrollPeriodListEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create payroll period */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PayrollPeriodWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PayrollPeriodEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payslips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payslips */
        get: {
            parameters: {
                query?: {
                    payroll_period_id?: number;
                    employee_id?: number;
                    page?: components["parameters"]["page"];
                    per_page?: components["parameters"]["perPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PayslipPaginatedEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create payslip */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PayslipWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PayslipEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payslips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update payslip amounts
         * @description Adjusts gross, deductions, and net only. Does not change employee, period, meta, or status.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PayslipAmountsPatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PayslipEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/payslips/notify-period": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify employees for all payslips in a payroll period
         * @description Records one `payslip.available` notification per payslip matching scope (and optional department filter).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PayslipNotifyPeriodWrite"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PayslipNotifyPeriodEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payslips/{id}/notify-employee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify employee (payslip available in portal)
         * @description Records a portal notification for the payslip employee (same kind as on create). Idempotent in behavior: each call adds a notification row.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PayslipNotifyEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payslips/preview-previsional": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview previsional deduction (no persistence)
         * @description Suggests ONP or AFP Integra/Prima commission from legal parameters; does not write payslips.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PrevisionalPreviewWrite"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrevisionalPreviewEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/exports/payroll-payslips.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download payslip PDFs as ZIP for a payroll period
         * @description Returns a ZIP with one PDF per payslip (same template as GET /payslips/{id}/pdf), scoped by department access and optional department_id filter. Requires reports.export and payroll.view.
         */
        get: {
            parameters: {
                query: {
                    payroll_period_id: number;
                    department_id?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ZIP attachment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assets */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    status?: string;
                    employee_id?: number;
                    page?: components["parameters"]["page"];
                    per_page?: components["parameters"]["perPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetPaginatedEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create asset */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssetWrite"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update asset */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssetWritePartial"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/settings/mail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get persisted SMTP settings
         * @description Requires settings.smtp. Password is never returned; use password_set.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MailSettingsEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        /**
         * Update SMTP settings
         * @description Requires settings.smtp. Omit password to leave unchanged; send empty string to clear.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MailSettingsWrite"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MailSettingsEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/mail/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send test email
         * @description Requires settings.smtp. Uses persisted SMTP when enabled and host is set; otherwise default mailer (e.g. MAIL_* / log).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MailTestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MailTestEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            message: string;
            code?: string;
            errors?: {
                [key: string]: string[];
            };
        };
        PaginationMeta: {
            current_page?: number;
            per_page?: number;
            total?: number;
            last_page?: number;
        };
        PaginationLinks: {
            first?: string | null;
            last?: string | null;
            prev?: string | null;
            next?: string | null;
        } | null;
        /** @description Role slug assigned to the user. Known seeded values: superadmin_rrhh, admin_rrhh, jefe_area, empleado. Additional slugs may appear if new roles are added in the database. */
        AppRole: string;
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginEnvelope: {
            data: {
                token: string;
                /** @example Bearer */
                token_type: string;
                user: components["schemas"]["UserMe"];
            };
        };
        UserMe: {
            id: number;
            name: string;
            email: string;
            role?: components["schemas"]["AppRole"];
            /** @description Effective RBAC permission slugs for the current user */
            permissions?: string[];
            avatar_path?: string | null;
            department_id?: number | null;
            department?: components["schemas"]["Department"] | null;
            employee?: null | {
                id: number;
                full_name: string;
            };
        };
        UserMeEnvelope: {
            data: components["schemas"]["UserMe"];
        };
        Department: {
            id: number;
            name: string;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        DepartmentListEnvelope: {
            data: components["schemas"]["Department"][];
        };
        DepartmentWrite: {
            name: string;
        };
        DepartmentEnvelope: {
            data: components["schemas"]["Department"];
        };
        /** @enum {string} */
        EmployeeStatus: "activo" | "suspendido" | "cesado" | "vacaciones";
        Employee: {
            id: number;
            user_id?: number | null;
            department_id?: number | null;
            manager_id?: number | null;
            full_name: string;
            dni: string;
            /** Format: date */
            birth_date?: string | null;
            education_level?: string | null;
            degree?: string | null;
            phone?: string | null;
            personal_email?: string | null;
            address?: string | null;
            emergency_contact_name?: string | null;
            emergency_contact_phone?: string | null;
            bank?: string | null;
            bank_account?: string | null;
            pension_fund?: string | null;
            position?: string | null;
            modality?: string | null;
            schedule?: string | null;
            salary?: string | null;
            contract_type?: string | null;
            /** Format: date */
            contract_start?: string | null;
            /** Format: date */
            contract_end?: string | null;
            status: components["schemas"]["EmployeeStatus"];
            photo_path?: string | null;
            /** @description Public avatar URL of linked system user (e.g. Google); for UI when photo_path is empty */
            linked_user_avatar_path?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        EmployeeWrite: {
            user_id?: number | null;
            department_id?: number | null;
            manager_id?: number | null;
            full_name: string;
            dni: string;
            /** Format: date */
            birth_date?: string | null;
            education_level?: string | null;
            degree?: string | null;
            phone?: string | null;
            /** Format: email */
            personal_email?: string | null;
            address?: string | null;
            emergency_contact_name?: string | null;
            emergency_contact_phone?: string | null;
            bank?: string | null;
            bank_account?: string | null;
            pension_fund?: string | null;
            position?: string | null;
            modality?: string | null;
            schedule?: string | null;
            salary?: number | null;
            contract_type?: string | null;
            /** Format: date */
            contract_start?: string | null;
            /** Format: date */
            contract_end?: string | null;
            status?: components["schemas"]["EmployeeStatus"];
            photo_path?: string | null;
        };
        /** @description Same fields as EmployeeWrite but all optional for PATCH */
        EmployeeWritePartial: {
            [key: string]: unknown;
        };
        EmployeeEnvelope: {
            data: components["schemas"]["Employee"];
        };
        /** @enum {string} */
        EmployeeTerminationStatus: "borrador" | "confirmado";
        EmployeeTermination: {
            id: number;
            employee_id: number;
            status: components["schemas"]["EmployeeTerminationStatus"];
            exit_reason: string;
            /** Format: date */
            effective_date: string;
            notes?: string | null;
            meta?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            confirmed_at?: string | null;
            confirmed_by_user_id?: number | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        EmployeeTerminationWrite: {
            exit_reason: string;
            /** Format: date */
            effective_date: string;
            notes?: string | null;
            /**
             * @description When true, confirm immediately and set employee to cesado
             * @default true
             */
            confirm: boolean;
        };
        EmployeeTerminationEnvelope: {
            data: components["schemas"]["EmployeeTermination"];
        };
        EmployeeTerminationLiquidationComponents: {
            cts?: string | null;
            vacation_truncated?: string | null;
            gratification_truncated?: string | null;
            total?: string | null;
        };
        EmployeeTerminationLiquidationSnapshot: {
            schema_version: number;
            /** Format: date */
            reference_date: string;
            components: components["schemas"]["EmployeeTerminationLiquidationComponents"];
            notes?: string | null;
            meta?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            recorded_at: string;
        };
        EmployeeTerminationLiquidationWrite: {
            /** @enum {integer} */
            schema_version: 1;
            /** Format: date */
            reference_date: string;
            components: {
                cts?: number | null;
                vacation_truncated?: number | null;
                gratification_truncated?: number | null;
                total?: number | null;
            };
            notes?: string | null;
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        EmployeeTerminationLiquidationEnvelope: {
            data: null | components["schemas"]["EmployeeTerminationLiquidationSnapshot"];
        };
        EmployeeTerminationLiquidationSavedEnvelope: {
            data: components["schemas"]["EmployeeTerminationLiquidationSnapshot"];
        };
        EmployeeTerminationChecklistItem: {
            id: number;
            code: string;
            title: string;
            description?: string | null;
            sort_order: number;
        };
        EmployeeTerminationChecklistTask: {
            id: number;
            completed: boolean;
            /** Format: date-time */
            completed_at?: string | null;
            completed_by_user_id?: number | null;
            notes?: string | null;
            item: components["schemas"]["EmployeeTerminationChecklistItem"];
        };
        /** @description Assets currently linked to the employee (employee_id). Pending return is implied by assignment; formal return workflow may clear employee_id or change status in a later release. */
        TerminationOffboardingAssignedAssets: {
            has_pending_assigned_assets: boolean;
            assigned_count: number;
            assets: components["schemas"]["Asset"][];
        };
        EmployeeTerminationChecklistListEnvelope: {
            data: {
                termination_id: number;
                tasks: components["schemas"]["EmployeeTerminationChecklistTask"][];
                assigned_assets: components["schemas"]["TerminationOffboardingAssignedAssets"];
            };
        };
        EmployeeTerminationChecklistTaskWrite: {
            completed: boolean;
            notes?: string | null;
        };
        EmployeeTerminationChecklistTaskEnvelope: {
            data: components["schemas"]["EmployeeTerminationChecklistTask"];
        };
        EmployeePaginatedEnvelope: {
            data: components["schemas"]["Employee"][];
            meta: components["schemas"]["PaginationMeta"];
            links: components["schemas"]["PaginationLinks"];
        };
        /** @enum {string} */
        EmployeeDocumentType: "antecedentes" | "cv" | "medical_exam" | "contract" | "termination_certificate";
        EmployeeDocument: {
            id: number;
            employee_id: number;
            type: components["schemas"]["EmployeeDocumentType"];
            file_path: string;
            /** Format: date-time */
            uploaded_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        EmployeeDocumentEnvelope: {
            data: components["schemas"]["EmployeeDocument"];
        };
        EmployeeDocumentListEnvelope: {
            data: components["schemas"]["EmployeeDocument"][];
        };
        /** @enum {string} */
        AttendanceStatus: "asistido" | "recuperacion" | "tardanza_j" | "tardanza_nj" | "falta_j" | "falta_nj" | "vacaciones";
        AttendanceRecord: {
            id: number;
            employee_id: number;
            /** Format: date */
            record_date: string;
            status: components["schemas"]["AttendanceStatus"];
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        AttendanceWrite: {
            employee_id: number;
            /** Format: date */
            record_date: string;
            status: components["schemas"]["AttendanceStatus"];
        };
        AttendancePatch: {
            status: components["schemas"]["AttendanceStatus"];
        };
        AttendanceEnvelope: {
            data: components["schemas"]["AttendanceRecord"];
        };
        AttendancePaginatedEnvelope: {
            data: components["schemas"]["AttendanceRecord"][];
            meta: components["schemas"]["PaginationMeta"];
            links: components["schemas"]["PaginationLinks"];
        };
        /** @enum {string} */
        VacationStatus: "pendiente" | "aprobado" | "rechazado";
        VacationRequest: {
            id: number;
            employee_id: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            days: number;
            status: components["schemas"]["VacationStatus"];
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        VacationWrite: {
            employee_id: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            days: number;
            status?: components["schemas"]["VacationStatus"];
        };
        VacationStatusPatch: {
            status: components["schemas"]["VacationStatus"];
        };
        VacationEnvelope: {
            data: components["schemas"]["VacationRequest"];
        };
        VacationPaginatedEnvelope: {
            data: components["schemas"]["VacationRequest"][];
            meta: components["schemas"]["PaginationMeta"];
            links: components["schemas"]["PaginationLinks"];
        };
        PayrollPeriod: {
            id: number;
            year: number;
            month: number;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        PayrollPeriodWrite: {
            year: number;
            month: number;
        };
        PayrollPeriodEnvelope: {
            data: components["schemas"]["PayrollPeriod"];
        };
        PayrollPeriodListEnvelope: {
            data: components["schemas"]["PayrollPeriod"][];
        };
        LegalParameterCatalogItem: {
            key: string;
            label_es: string;
            unit: string;
            value: string | null;
        };
        PayslipBreakdownLine: {
            /** @description Stable line code for integrations (e.g. base */
            code: string;
            /** @description Human-readable label for the slip. */
            label: string;
            /** @description Amount in PEN; not cross-validated against totals in Etapa B. */
            amount: number;
        };
        PrevisionalPreviewWrite: {
            employee_id: number;
            payroll_period_id: number;
            gross_amount: number;
        };
        PrevisionalPreviewData: {
            /** @enum {string} */
            status: "ok" | "unsupported_regime" | "missing_legal_rate";
            pension_fund_original?: string | null;
            /** @description Resolved regime slug (onp, afp_integra, afp_prima) or unsupported. */
            regime_resolved: string;
            legal_parameter_key?: string | null;
            ratio?: string | null;
            base_amount: string;
            /** Format: date */
            reference_date: string;
            amount?: string | null;
            proposed_deduction_line?: components["schemas"]["PayslipBreakdownLine"] | null;
        };
        PrevisionalPreviewEnvelope: {
            data: components["schemas"]["PrevisionalPreviewData"];
        };
        /** @description Stored under meta.payslip_breakdown. Coexists with meta.legal_parameters_context (server-set). Line amounts are informational until automated legal calculations exist. */
        PayslipBreakdown: {
            /**
             * @description Breakdown schema version.
             * @enum {integer}
             */
            schema_version: 1;
            notes?: string | null;
            earnings?: components["schemas"]["PayslipBreakdownLine"][];
            deductions?: components["schemas"]["PayslipBreakdownLine"][];
            employer_contributions?: components["schemas"]["PayslipBreakdownLine"][];
        };
        Payslip: {
            id: number;
            payroll_period_id: number;
            employee_id: number;
            gross_amount: string;
            deductions_amount: string;
            net_amount: string;
            status: string;
            /** @description May include payslip_breakdown (see PayslipBreakdown) and custom keys. legal_parameters_context is populated on create by the server. */
            meta?: {
                [key: string]: unknown;
            } | null;
            /**
             * Format: date
             * @description Last calendar day of the payroll month; reference date for legal parameter vigencia.
             */
            payroll_legal_reference_date?: string;
            /** @description Parameters effective at payroll_legal_reference_date (frozen in meta on create when applicable). */
            legal_parameters_snapshot?: components["schemas"]["LegalParameterCatalogItem"][];
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        /** @description Amount fields only; deductions_amount defaults to 0 when omitted (same as create). */
        PayslipAmountsPatch: {
            gross_amount: number;
            deductions_amount?: number;
            net_amount: number;
        };
        PayslipWrite: {
            payroll_period_id: number;
            employee_id: number;
            gross_amount: number;
            deductions_amount?: number;
            net_amount: number;
            status?: string;
            /**
             * @description When true, server merges a previsional deduction line into meta.payslip_breakdown from legal parameters (same logic as preview-previsional). Returns 422 if regime unsupported or rate missing. Does not change gross/deductions/net columns.
             * @default false
             */
            apply_previsional_assist: boolean;
            /** @description Optional payslip_breakdown (PayslipBreakdown). Server merges legal_parameters_context on create. If apply_previsional_assist is true, previsional lines replace prior previsional_* deduction codes only. */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        PayslipEnvelope: {
            data: components["schemas"]["Payslip"];
        };
        PayslipNotifyResult: {
            notified: boolean;
        };
        PayslipNotifyEnvelope: {
            data: components["schemas"]["PayslipNotifyResult"];
        };
        PayslipNotifyPeriodWrite: {
            payroll_period_id: number;
            department_id?: number | null;
        };
        PayslipNotifyPeriodResult: {
            notified_count: number;
        };
        PayslipNotifyPeriodEnvelope: {
            data: components["schemas"]["PayslipNotifyPeriodResult"];
        };
        PayslipPaginatedEnvelope: {
            data: components["schemas"]["Payslip"][];
            meta: components["schemas"]["PaginationMeta"];
            links: components["schemas"]["PaginationLinks"];
        };
        Asset: {
            id: number;
            type: string;
            brand?: string | null;
            model?: string | null;
            serial_number?: string | null;
            description?: string | null;
            employee_id?: number | null;
            status: string;
            observations?: string | null;
            /** Format: date */
            assigned_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        AssetWrite: {
            type: string;
            brand?: string | null;
            model?: string | null;
            serial_number?: string | null;
            description?: string | null;
            employee_id?: number | null;
            status: string;
            observations?: string | null;
            /** Format: date */
            assigned_at?: string | null;
        };
        AssetWritePartial: {
            [key: string]: unknown;
        };
        AssetEnvelope: {
            data: components["schemas"]["Asset"];
        };
        AssetPaginatedEnvelope: {
            data: components["schemas"]["Asset"][];
            meta: components["schemas"]["PaginationMeta"];
            links: components["schemas"]["PaginationLinks"];
        };
        MailSettings: {
            enabled: boolean;
            host?: string | null;
            port?: number | null;
            /** @enum {string|null} */
            encryption?: "tls" | "ssl" | null;
            username?: string | null;
            password_set: boolean;
            /** Format: email */
            from_address?: string | null;
            from_name?: string | null;
        };
        MailSettingsEnvelope: {
            data: components["schemas"]["MailSettings"];
        };
        MailSettingsWrite: {
            enabled: boolean;
            host?: string | null;
            port?: number | null;
            /** @enum {string|null} */
            encryption?: "tls" | "ssl" | "" | null;
            username?: string | null;
            password?: string | null;
            /** Format: email */
            from_address?: string | null;
            from_name?: string | null;
        };
        MailTestRequest: {
            /** Format: email */
            to: string;
        };
        MailTestEnvelope: {
            data: {
                sent: boolean;
                /** Format: email */
                to: string;
            };
        };
        UserAdmin: {
            id: number;
            name: string;
            email: string;
            role?: components["schemas"]["AppRole"];
            role_id?: number | null;
            department_id?: number | null;
            is_active: boolean;
            /** Format: date-time */
            created_at?: string | null;
        };
        UserAdminPaginatedEnvelope: {
            data: components["schemas"]["UserAdmin"][];
            meta: components["schemas"]["PaginationMeta"];
            links: components["schemas"]["PaginationLinks"];
        };
        UserAdminCreate: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            role_id: number;
            department_id?: number | null;
        };
        UserAdminUpdate: {
            name: string;
            /** Format: email */
            email: string;
            role_id: number;
            department_id?: number | null;
            password?: string | null;
        };
        UserAdminActiveBody: {
            is_active: boolean;
        };
        UserAdminEnvelope: {
            data: components["schemas"]["UserAdmin"];
        };
        PermissionListItem: {
            id: number;
            slug: string;
            name?: string | null;
        };
        RoleListItem: {
            id: number;
            slug: string;
            name?: string | null;
            permissions: components["schemas"]["PermissionListItem"][];
        };
        RoleListEnvelope: {
            data: components["schemas"]["RoleListItem"][];
        };
        LegalParameterListItem: {
            key: string;
            label_es: string;
            unit: string;
            description?: string | null;
            value?: string | null;
            /** Format: date */
            effective_from?: string | null;
            /** Format: date */
            effective_to?: string | null;
            value_id?: number | null;
        };
        LegalParametersListEnvelope: {
            data: components["schemas"]["LegalParameterListItem"][];
            /** Format: date */
            at: string;
        };
        LegalParameterUpdateBody: {
            value: number;
            /** Format: date */
            effective_from: string;
            /** Format: date */
            effective_to?: string | null;
        };
        LegalParameterEnvelope: {
            data: components["schemas"]["LegalParameterListItem"];
        };
    };
    responses: {
        /** @description Unauthenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        idPath: number;
        page: number;
        perPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
